<!DOCTYPE html>
<html lang="en">

<head>
    <?php include "head.inc.phtml"; ?>
    <title>listado</title>
</head>

<body>
    <div class="container">
        <?php include "header.inc.phtml" ?>
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page"><a href=".">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Borrado</li>
            <li class="breadcrumb-item active" aria-current="page">Efectuado</li>
        </ol>
        <div class="alert alert-primary" role="alert">
            <h4 class="alert-heading">Borrado efectuado</h4>
            <div>
                <a class="btn btn-primary" href="?controller=listado">Volver al listado</a>
            </div>
        </div>
    </div>
</body>

</html>