<!DOCTYPE html>
<html lang="en">
<head>
    <?php include "head.inc.phtml"; ?>
    <title>listado</title>
</head>
<body>
    <div class="container">
        <?php include "header.inc.phtml" ?>
        <form action="index.php?controller=insertar" method="POST">
            <div class="form-group">
                <label for="nombreinput">Nombre: <i class="fa fa-asterisk"></i></label>
                <input type="text" class="form-control" id="nombreinput" name="nombre" value="<?=$nombre?>">
                <span class="text-warning"><?=$error_nombre;?></span>
            </div>
            <div class="form-group">
                <label for="pesoinput">Peso:</label>
                <input type="number" class="form-control" id="pesoinput" min="0" name="peso" value="<?=$peso?>">
            </div>
            <div class="form-group">
                <label for="radioinput">Radio:</label>
                <input type="number" class="form-control" id="radioinput" min="0" name="radio" value="<?=$radio?>">
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
        <br>
        <i class="fa fa-asterisk"></i> Requerido
    </div>
</body>

</html>