<!DOCTYPE html>
<html lang="en">

<head>
    <?php include "head.inc.phtml"; ?>
    <title>listado</title>
</head>

<body>
    <div class="container">
        <?php include "header.inc.phtml" ?>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Home</li>
            </ol>
        </nav>
        <p class="text-right"><a href="?controller=nuevo" class="btn btn-primary"><i class="fa fa-plus"></i> Nuevo</a></p>
        <table class="table">
            <tr>
                <th>id</th>
                <th>Nombre</th>
                <th>Peso</th>
                <th>Radio</th>
                <th>Superficie</th>
                <th>Acciones</th>
            </tr>
            <?php foreach ($planetas as $planeta) { ?>
                <tr>
                    <th><?= $planeta->id ?></th>
                    <td><?= $planeta->nombre ?></td>
                    <td><?= $planeta->peso ?></td>
                    <td><?= $planeta->radio ?></td>
                    <td><?= sprintf("%.2f", $planeta->calcularSuperficie()) ?></td>
                    <td>
                        <a title="editar" class="btn btn-secondary text-light" href="?controller=modificacion&id=<?= $planeta->id ?>"><i class="fa fa-edit"></i></a>
                        <a title="borrar" class="btn btn-danger text-light" href="?controller=borrado&id=<?= $planeta->id ?>"><i class="fa fa-eraser"></i></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
</body>

</html>