<!DOCTYPE html>
<html lang="en">

<head>
    <?php include "head.inc.phtml"; ?>
    <title>listado</title>
</head>

<body>
    <div class="container">
        <?php include "header.inc.phtml" ?>
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page"><a href=".">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Modificar planeta</li>
        </ol>
        <?php if ($error_msg) { ?>
            <div class="alert alert-danger" role="alert">
                <?= $error_msg ?>
            </div>
        <?php } ?>
        <form action="?controller=modificacion" method="POST">
            <input type="hidden" name="id" value="<?= $id ?>">
            <div class="form-group row">
                <label for="nombreinput" class="col-md-3">Nombre: </label>
                <input type="text" class="form-control col-md-9" id="nombreinput" name="nombre" value="<?= $planeta->nombre ?>">
            </div>
            <div class="form-group row">
                <label for="pesoinput" class="col-md-3">Peso:</label>
                <input type="number" class="form-control col-md-9" id="pesoinput" min="0" name="peso" value="<?= $planeta->peso ?>">
            </div>
            <div class="form-group row">
                <label for="radioinput" class="col-md-3">Radio:</label>
                <input type="number" class="form-control col-md-9" id="radioinput" min="0" name="radio" value="<?= $planeta->radio ?>">
            </div>
            <div class="row">
                <div class="offset-md-3 col-md-9"><button type="submit" class="btn btn-primary">Enviar</button> <a href="?controller=listado" class="btn btn-secondary">Cancelar</a>
                </div>
        </form>

        <div class="alert alert-info mt-3">
            Nota técnica: el id está en un <code>&lt;input type="hidden" name="id" value="<?= $id ?>"&gt;</code>
        </div>
    </div>
</body>

</html>