<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exito</title>
</head>

<body>
    <div style="margin:3px 20px;">
        <h1>Instalación de app Planetas</h1>
        <hr>
        <p>Se ordenó la ejecución del script de creación de la bd.</p>
        <p>Se creó el fichero config.ini con los parámetros de conexión</p>
        <a href=".">Entrar a la app</a>
    </div>
</body>

</html>